### ISSUE TITLE
Extra options for placement of widgets

### ISSUE THREAD

**Issue by DriesArnolds** [yannickoo/minimal_share#1]
I love the minimal design of this module and the fact that you can style it any way you wish.

It would be nice to be able to do the following things:
- define on which content types widget shows
- hide for specific nodes (thank you pages etc)
- place widgets in block
- display widgets one top or bottom of node (could also be done with block of course)
- display widgets on teaser or full content or both

**Comment by yannickoo** [comment]
Sorry for the delay, here my response but first thank you for your feedback, nice input!

> define on which content types widget shows

You can easily enable / disable the widget on the _Manage display_ page for each content type.

> hide for specific nodes (thank you pages etc)

This is a good point! I will think about that and implement it later.

> place widgets in block

You want to share the current page then? How many blocks should be provided? Is one enough?

> display widgets one top or bottom of node (could also be done with block of course)

This can be also set on the _Mange display_ page, just move the widget to the top via drag and drop.

> display widgets on teaser or full content or both

Same here, go to your _Manage display_ page and click _Teaser_ in the sub tabs, there you can disable the Minimal Share field.

I'm going to convert your remarks to issues now :)
