### ISSUE TITLE
Shared image in Facebook does not correspond

### ISSUE THREAD

**Issue by glourencoglourenco** [yannickoo/minimal_share#10]
Hi, image of the node shown when sharing, is posted in facebook with the first image of the page, in this case, webpage logo.
thanks!

**Comment by yannickoo** [comment]
You can easily control the image which is posted to Facebook by settings an `og:image` meta tag. You can do this by installing the [Metatag](https://www.drupal.org/project/metatag) module. When you just want to see what Facebook gets from your page you can check out the [URL Debugger](https://developers.facebook.com/tools/debug/) that tool shows you which image is used when sharing.
