### ISSUE TITLE
Add WhatsApp support

### ISSUE THREAD

**Issue by IT-Cru** [yannickoo/minimal_share#11]
Add Support for WhatsApp (iPhone / Android)

https://www.whatsapp.com/faq/de/iphone/23559013
https://www.whatsapp.com/faq/en/android/28000012

**Comment by IT-Cru** [comment]
https://gist.github.com/IT-Cru/8a975fd0a9b2be268c51#file-minimal_share-whatsapp_support-12-1-patch

**Comment by yannickoo** [comment]
I can work on this but for adding WhatsApp provider we need following things:
- [x] Add to `minimal_share_minimal_share_services`
- [x] Provide styling for new sharing link
- [x] Add [icon](http://fontello.com/#search=whatsapp) for new provider
- [x] Hide WhatsApp sharing link on non-mobile devices (this would not make sense for desktop users)
