### ISSUE TITLE
Custom button possible (e.g. whatsapp)

### ISSUE THREAD

**Issue by magnolia61** [yannickoo/minimal_share#14]
A nice addition would be to add the possibility to add a custom button.
In our case we would love a whatsapp button.

Thanks for this nice clean extension!

**Comment by magnolia61** [comment]
BTW. now that I further look into it, it seems you support whatsapp. Only that option is not shown in my configuration. Any idea why not?

**Comment by yannickoo** [comment]
The WhatsApp service provider is already in the latest version of Minimal Share. You can download it [here](http://ftp.drupal.org/files/projects/minimal_share-7.x-1.x-dev.tar.gz).

Note: You will not see it on a normal desktop browser, only on mobile devices.

When you want to add a new service provider you need to use [hook_minimal_share_services](https://github.com/yannickoo/minimal_share/blob/7.x-1.x/minimal_share.api.php#L8) through a custom module.

**Comment by magnolia61** [comment]
I downloaded your dev version, first removed the other version, cleared caches, but I cannot see whatsapp in the configuration menu. Should it be there? /admin/config/user-interface/minimal-share
(or also only when views from a mobile device?)

**Comment by yannickoo** [comment]
I just installed the latest version through [simplytest.me](https://simplytest.me/) and here you can see WhatsApp in the configuration:

<img width="327" alt="screen shot 2015-10-03 at 16 56 50" src="https://cloud.githubusercontent.com/assets/1086961/10263466/27b14d7a-69f0-11e5-88da-8ed29cce49ee.png">

After I enabled WhatsApp I could see it in the preview box:

<img width="855" alt="screen shot 2015-10-03 at 16 57 00" src="https://cloud.githubusercontent.com/assets/1086961/10263469/407b8532-69f0-11e5-8fc4-cab18c0280a6.png">
