### ISSUE TITLE
Twitter intent 'status' parameter should be 'text'

### ISSUE THREAD

**Issue by pixelwhip** [yannickoo/minimal_share#19]
According to the official intent docs, the proper query parameter for Twitter intents is `text` not `status` https://dev.twitter.com/web/tweet-button/web-intent

status works when the intent is opening in twitter.com in a browser but fails when opening in native Twitter app.

**Comment by pixelwhip** [comment]
https://github.com/pixelwhip/minimal_share/pull/1

**Comment by pixelwhip** [comment]
Pull Request #20

**Comment by yannickoo** [comment]
I figured out that it's necessary to set the `url` query parameter as well, fixed this in 8ffeba6811c2a3e278f0df0d5978fb34bf8700fb.

Thank you for your pull request :)
