### ISSUE TITLE
provide a block for general sharing

### ISSUE THREAD

**Issue by yannickoo** [yannickoo/minimal_share#2]
We could implement a block which displays sharing buttons for the current page. This was mentioned in #1.

**Comment by ghost** [comment]
Hi, 

couldn't wait for your block implementation and ended up adding these to module:
(I know - not a good idea to modify a module this way)

/**
- Implements hook_block_info().
  */
  function minimal_share_block_info() {
  $blocks = array();
  $blocks['minimal_share'] = array(
    'info' => t('Minimal share'),
  );
  
  return $blocks;
  }

/**
- Implements hook_block_view().
  */
  function minimal_share_block_view($delta='') {
  $block = array();
  
  switch($delta) {
    case 'minimal_share' :
      $block['content'] = ms_block_view();
      break;
  }
  
  return $block;
  }

/**
- Custom function to assemble renderable array for block content.
- Returns a renderable array with the block content.
- @return
-   returns a renderable array of block content.
  */
  function ms_block_view() {
  $block = array();

//   list(, , $bundle) = entity_extract_ids($type, $entity);
//   $extra_fields = field_extra_fields_get_display($type, $bundle, $view_mode);
// 
//   if (isset($extra_fields['minimal_share']) && $extra_fields['minimal_share']['visible']) {
//     $entity->content['minimal_share'] = minimal_share_field($type, $entity);
//   }
//  dsm('ms_block_view: ');
  $share_services = minimal_share_block_content($entity_type, $entity);
//   dsm($share_services);

  // Block output in HTML with div wrapper
  $block = array(
    'minimal-share' => array(
      '#type' => 'markup',
      '#markup' => $share_services['#value'],
      '#suffix' => '',
    ),
  );

  return $block;
}

/**
- Extra field callback.
  - Copy of original function - parameters removed & url & title modified
    */
    function minimal_share_block_content() {
    // Get all available service information.
    $settings = minimal_share_settings();

//   $uri = entity_uri($entity_type, $entity);
//   $url = drupal_encode_path(url($uri['path'], array('absolute' => TRUE)));
//   $title = drupal_encode_path(entity_label($entity_type, $entity));

  $path = isset($_GET['q']) ? $_GET['q'] : '<front>';
    $url = url($path, array('absolute' => TRUE));
  $title = drupal_get_title();

  $element = array(
    '#type' => 'html_tag',
    '#tag' => 'p',
    '#attributes' => array('class' => array('minimal-share')),
    '#value' => '',
    '#attached' => array(
      'css' => array(
        drupal_get_path('module', 'minimal_share') . '/css/minimal-share.css',
      ),
      'js' => array(
        drupal_get_path('module', 'minimal_share') . '/js/minimal-share.js',
      ),
    ),
  );

  foreach ($settings['services'] as $service_name => $service) {
    if (!$service['enabled']) {
      continue;
    }

```
$service['url'] = str_replace(array('[title]', '[url]'), array($title, $url), $service['url']);

// Set default label type.
if (!isset($service['label_type'])) {
  $service['label_type'] = 'name';
}

// Load count only if necessary.
if ($service['label_type'] == 'name_count' || $service['label_type'] == 'custom' && strpos($service['custom'], '[count]') !== FALSE) {
  $count = minimal_share_count($service_name, $url);
}

switch ($service['label_type']) {
  case 'name':
    $service['label'] = $service['title'];
    break;

  case 'icon':
    $service['label'] = '';
    $element['#attached']['css'][] = drupal_get_path('module', 'minimal_share') . '/css/minimal-share-icons.css';
    break;

  case 'name_count':
    $service['label'] = '<span class="title">' . $service['title'] . '</span>';

    if ($count || !$count && !$service['hide_zero']) {
      $service['label'] .= ' <span class="count">(' . $count . ')</span>';
    }
    break;

  case 'custom':
    // Replace [count] token with real count.
    if (minimal_share_count_callback_exists($service) && strpos($service['custom'], '[count]') !== FALSE) {
      $service['custom'] = str_replace('[count]', $count, $service['custom']);
    }

    $service['label'] = check_plain($service['custom']);
    break;
}

$link_options = array(
  'html' => TRUE,
  'external' => TRUE,
  'attributes' => array(
    'class' => array($service_name),
  ),
);

if ($service['label_type'] == 'icon') {
  $link_options['attributes']['class'][] = 'icon';
}

// Add data attributes for size.
foreach (array('width', 'height') as $property) {
  if (isset($service['size'][$property])) {
    $link_options['attributes']['data-' . $property] = $service['size'][$property];
  }
}

$element['#value'] .= l($service['label'], $service['url'], $link_options);
```

  }

  return $element;
}
