### ISSUE TITLE
Share to pinterest dont work

### ISSUE THREAD

**Issue by kitikonti** [yannickoo/minimal_share#8]
The first problem is the url encoding. Pinterest expect a complete url encoded url. Currently i get something like:
http%253A//www.example.com/my-amazing-node
but only something like the following will work:
http%25253A%2F%2Fwww.example.com%2Fmy-amazing-node

The secound problem is that pinterest dont gets an image. I get a failure like this (german):
Du musst ein Bild hochladen oder den Parameter „image_url“ angeben
Is there a other way i could serve the image than the image_url? Because when i check the module code i dont find any information for this parameter.

**Comment by yannickoo** [comment]
It was easy to fix the first problem but for the `image_url` thing we need to add a select list or a text field so that the image field can be selected. I will work on this next week :)

**Comment by kitikonti** [comment]
I dont understand the commit? Does share to pinterest work now or was this just the preperation to get it working?

**Comment by yannickoo** [comment]
Just install the Token module and then you can select a token for the image which shall be used when sharing to Pinterest.

![screen shot 2015-06-02 at 12 17 56](https://cloud.githubusercontent.com/assets/1086961/7933720/6f21381c-0921-11e5-8367-32a97cf2bfe8.png)

**Comment by kitikonti** [comment]
Ok thanks got it, but took me a while to get a working token because i am using a multivalue image field. The token in this case has to look like [node:field-images:0:file:url].
But i have to say that there are two problems. First, what if i have different image fields? I can just add one token, in my case for real estate. But i also have articles with a different image field, so i have to use a different token, or am i wrong?
And the next thing is, that there is a Problem with the generated description. It seem only for twitter and pinterest. For example i get titles like this: Fuschl%20am%20See%3A%20Sensational%20new%20penthouse%20with%20lake%20view%20for%20sale%20
Don't know what this %20 means and where i come from? You can test this on my site: http://www.masterhomes.net/

Thanks for all your work, really great module.

**Comment by yannickoo** [comment]
Okay I think I will change the configuration later.

I fixed your other mentioned issues in [139ff97](https://github.com/yannickoo/minimal_share/commit/139ff972753caa95be75e76352a7d4a273404c3a) :)

**Comment by kitikonti** [comment]
Ok thanks, works now.
