### ISSUE TITLE
Share to linkedin not working

### ISSUE THREAD

**Issue by AlessioPellegrini** [yannickoo/minimal_share#9]
Hello,
the share to linkedin won't work on my installation, if I'm logged to linkedin and I click on the share icon I always receive an error.

**Comment by yannickoo** [comment]
Could you please add more information about the error? This makes it easier to fix :)

**Comment by AlessioPellegrini** [comment]
Hello,
If I disconnect my account on likedin and I click on the "minimal share icon" it appears a pop up
for making login; if I try to make login I receive an error like this:
"We are sorry. There was a problem and your request was not completed. Close this window and try again"

If I previosly login in my linkedin accout and I click on the "minimal share icon" the error message appears directly.

Drupal's error log is empty.

I'm using linux mint 17 and the latest version of Chrome stable.

Here is a link to the site: http://www.matteo.pointnet.info/blogs/matteo

Thanks
